blank_issues_enabled: false
contact_links:
    - name: ❗️ All other issues
      url: https://github.com/Tada5hi/hapic/discussions
      about: |
          Please use GitHub Discussions for other issues and asking questions.
