# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches:
            - '**'

env:
    PRIMARY_NODE_VERSION: 18

defaults:
    run:
        shell: bash

jobs:
    install:
        name: Checkout and Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}

    build:
        name: Build Packages
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}
            - name: Build
              uses: ./.github/actions/build

    lint:
        name: lint Packages
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Lint
                run: |
                    npm run lint

    tests:
        name: Test Packages
        needs: [build]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: [
                    'client',
                    'harbor',
                    'oauth2'
                ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: Run tests
                run: |
                    npm run test --workspace=packages/${{matrix.package}} --if-present

    publish:
        name: Publish canary version
        needs: [lint, tests]
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2

            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.PRIMARY_NODE_VERSION }}

            -   name: Build
                uses: ./.github/actions/build

            -   name: NPM Identity
                env:
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                run: |
                    echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

            -   run: |
                    git fetch --prune --unshallow

            -   name: Publish all packages to npm
                run: npx lerna publish --loglevel=verbose --canary --exact --force-publish --yes --registry https://registry.npmjs.org
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Cleanup NPM Identity
                run: |
                    echo "" > .npmrc
